// Global data object to avoid CORS issues with file:// protocol
window.PORTFOLIO_DATA = {
    translations: {
        tr: {
            "nav-home": "Ana Sayfa",
            "nav-profile": "Hakkımda",
            "nav-experience": "Deneyim",
            "nav-projects": "Projeler",
            "nav-documents": "Dokümanlar",
            "hero-title": "Alper Kocasalih",
            "hero-subtitle": "Game Designer & Software Developer",
            "hero-status": "EU Work Permit | Remote Friendly | Available for New Opportunities 🚀",
            "hero-desc": "Istanbul Beykent Üniversitesi Dijital Oyun Tasarımı öğrencisi. Teknik problem çözme ve sistem mimarisi odaklı bir geliştirici adayı.",
            "profile-title": "Kişisel Bilgiler",
            "profile-edu": "Eğitim",
            "profile-uni": "Beykent Üniversitesi",
            "profile-dept": "Dijital Oyun Tasarımı",
            "profile-date": "2022 - Devam Ediyor",
            "profile-skills": "Yetenekler",
            "profile-tech": "Teknik Bilgi",
            "profile-tech-desc": "OOP, SOLID, Design Patterns, Game Mechanics, Technical QA, .NET Core, URP/Shader.",
            "exp-title": "EXPERIENCE",
            "exp-recontact-title": "Technical QA Analyst (Volunteer)",
            "exp-recontact-company": "Recontact Games",
            "exp-recontact-loc": "Istanbul, Türkiye",
            "exp-recontact-date": "Oct 2024 - Dec 2024",
            "exp-recontact-b1-title": "Deep-Level Logic Debugging",
            "exp-recontact-b1-desc": "Identified and documented critical back-end logic errors (including null-pointer/nmed exceptions) by analyzing the interaction between core code and gameplay systems.",
            "exp-recontact-b2-title": "Performance Benchmarking",
            "exp-recontact-b2-desc": "Conducted technical analysis of FPS output and frame-time consistency to determine their impact on gameplay mechanics and player input latency.",
            "exp-recontact-b3-title": "Technical Bug Reporting",
            "exp-recontact-b3-desc": "Provided high-fidelity reports for engineering teams, including root cause analysis of system-level crashes and mechanics failures.",

            "exp-netas-title": "Software & System Test Intern",
            "exp-netas-company": "Netaş Telekomünikasyon A.Ş.",
            "exp-netas-loc": "Istanbul, Türkiye",
            "exp-netas-date": "July 2025 - Sep 2025",
            "exp-netas-b1-title": "Stress & Load Testing",
            "exp-netas-b1-desc": "Conducted \"purpose-defying\" system usage tests to identify breaking points; monitored CPU/GPU load and hardware resource allocation under extreme conditions.",
            "exp-netas-b2-title": "AI System Verification",
            "exp-netas-b2-desc": "Tested AI Chatbot logic and response accuracy, ensuring functional stability and high-performance backend-frontend synchronization.",
            "exp-netas-b3-title": "Mobile Resource Analysis",
            "exp-netas-b3-desc": "Profiled real-time mobile data consumption and optimized technical systems to ensure high stability in data-driven interactive modules.",

            "exp-google-title": "Scholars Participant (Logic Engineering Focus)",
            "exp-google-company": "Google Yapay Zeka ve Teknoloji Akademisi",
            "exp-google-loc": "Istanbul, Türkiye",
            "exp-google-date": "Nov 2024 - Sep 2025",
            "exp-google-b1-title": "Logic Engineering",
            "exp-google-b1-desc": "Collaborated with cross-functional, randomized teams to engineer autonomous logic systems and AI-integrated features, focusing on algorithmic efficiency.",
            "exp-google-b2-title": "Agile Methodology",
            "exp-google-b2-desc": "Applied Agile/Scrum principles to manage product lifecycles and feature prioritization in high-pressure technical environments.",
            "exp-google-b3-title": "Data-Driven MVP Iteration",
            "exp-google-b3-desc": "Analyzed system performance metrics and user feedback loops to iterate on AI-integrated MVPs, optimizing core logic for scalability and market readiness.",

            "exp-tnc-title": "Project Management Intern",
            "exp-tnc-company": "TNC Group",
            "exp-tnc-loc": "Istanbul, Türkiye",
            "exp-tnc-date": "Apr 2025 - May 2025",
            "exp-tnc-b1-title": "Systematic Workflow Management",
            "exp-tnc-b1-desc": "Managed project integration workflows and task prioritization using a systematic approach aligned with real-world legal and regulatory standards.",
            "exp-tnc-b2-title": "Pipeline Coordination",
            "exp-tnc-b2-desc": "Facilitated communication between cross-functional teams, ensuring project documentation and delivery milestones met industry-standard quality benchmarks.",

            "projects-title": "Öne Çıkan Projeler",
            "proj-chess-title": "Project Chess",
            "proj-chess-desc": "Unity tabanlı, taktiksel masa oyunu. Sinerji motoru ve kart tabanlı drafting sistemi içerir. <br>Detaylar için tıklayınız..",
            "proj-billio-title": "Flutter_Billio",
            "proj-billio-desc": "Mobil abonelik ve finans takip uygulaması. Modern UI/UX prensipleriyle Flutter kullanılarak geliştirildi. <br>Detaylar için tıklayınız..",
            "docs-title": "Belgeler & Arşiv",
            "docs-desc": "İncelemek istediğiniz dökumanı seçiniz.",
            "doc-cv-title": "Güncel CV",
            "doc-cv-sub": "PDF Formatı",
            "doc-cert-title": "Sertifikalar",
            "doc-cert-sub": "Eğitim Belgeleri",
            "doc-port-title": "Portfolyo PDF",
            "doc-port-sub": "Tasarım Belgeleri",
            "doc-drive-title": "GDrive Arşivi",
            "doc-drive-sub": "Tüm Dosyalar",
            "theme-dark": "Karanlık Moda Geç",
            "theme-light": "Aydınlık Moda Geç",
            "close": "Kapat",
            "proj-chess-long-desc": "Project Chess, stratejik derinliği ve görsel zenginliği bir araya getiren modern bir masa oyunudur. Unity 6000'in gücünden yararlanan bu projede, oyuncular benzersiz yeteneklere sahip kartları draft ederek kendi stratejilerini oluştururlar. Sinerji motoru sayesinde farklı kart kombinasyonları, oyunun gidişatını tamamen değiştirebilen güçlü etkiler yaratır. Detaylı sistem tasarımı, hem yeni başlayanlar hem de deneyimli oyuncular için dengeli ve rekabetçi bir deneyim sunar.",
            "proj-billio-long-desc": "Flutter_Billio, modern mobil kullanıcıları için tasarlanmış kapsamlı bir abonelik ve finans takip uygulamasıdır. Flutter'ın gücünü kullanarak tek bir kod tabanıyla hem iOS hem de Android'de pürüzsüz bir deneyim sunar. Uygulama, harcama alışkanlıklarını analiz eder, yaklaşan ödemeleri hatırlatır ve kullanıcıların bütçelerini optimize etmelerine yardımcı olur. Glassmorphism ve minimal tasarım prensipleriyle hazırlanan arayüzü, finansal takibi sıkıcı bir işten keyifli bir deneyime dönüştürür.",
            "footer": "© 2026 Alper Kocasalih. Tüm hakları saklıdır."
        },
        en: {
            "nav-home": "Home",
            "nav-profile": "About Me",
            "nav-experience": "Experience",
            "nav-projects": "Projects",
            "nav-documents": "Documents",
            "hero-title": "Alper Kocasalih",
            "hero-subtitle": "Game Designer & Software Developer",
            "hero-status": "Junior Game Designer | Remote Friendly | Available for New Opportunities 🚀",
            "hero-desc": "Digital Game Design student at Istanbul Beykent University. Developer candidate focused on technical problem solving and system architecture.",
            "profile-title": "Personal Information",
            "profile-edu": "Education",
            "profile-uni": "Beykent University",
            "profile-dept": "Digital Game Design",
            "profile-date": "2022 - Present",
            "profile-skills": "Skills",
            "profile-tech": "Technical Knowledge",
            "profile-tech-desc": "OOP, SOLID, Design Patterns, Game Mechanics, Technical QA, .NET Core, URP/Shader.",
            "exp-title": "EXPERIENCE",
            "exp-recontact-title": "Technical QA Analyst (Volunteer)",
            "exp-recontact-company": "Recontact Games",
            "exp-recontact-loc": "Istanbul, Türkiye",
            "exp-recontact-date": "Oct 2024 - Dec 2024",
            "exp-recontact-b1-title": "Deep-Level Logic Debugging",
            "exp-recontact-b1-desc": "Identified and documented critical back-end logic errors (including null-pointer/nmed exceptions) by analyzing the interaction between core code and gameplay systems.",
            "exp-recontact-b2-title": "Performance Benchmarking",
            "exp-recontact-b2-desc": "Conducted technical analysis of FPS output and frame-time consistency to determine their impact on gameplay mechanics and player input latency.",
            "exp-recontact-b3-title": "Technical Bug Reporting",
            "exp-recontact-b3-desc": "Provided high-fidelity reports for engineering teams, including root cause analysis of system-level crashes and mechanics failures.",

            "exp-netas-title": "Software & System Test Intern",
            "exp-netas-company": "Netaş Telekomünikasyon A.Ş.",
            "exp-netas-loc": "Istanbul, Türkiye",
            "exp-netas-date": "July 2025 - Sep 2025",
            "exp-netas-b1-title": "Stress & Load Testing",
            "exp-netas-b1-desc": "Conducted \"purpose-defying\" system usage tests to identify breaking points; monitored CPU/GPU load and hardware resource allocation under extreme conditions.",
            "exp-netas-b2-title": "AI System Verification",
            "exp-netas-b2-desc": "Tested AI Chatbot logic and response accuracy, ensuring functional stability and high-performance backend-frontend synchronization.",
            "exp-netas-b3-title": "Mobile Resource Analysis",
            "exp-netas-b3-desc": "Profiled real-time mobile data consumption and optimized technical systems to ensure high stability in data-driven interactive modules.",

            "exp-google-title": "Scholars Participant (Logic Engineering Focus)",
            "exp-google-company": "Google Yapay Zeka ve Teknoloji Akademisi",
            "exp-google-loc": "Istanbul, Türkiye",
            "exp-google-date": "Nov 2024 - Sep 2025",
            "exp-google-b1-title": "Logic Engineering",
            "exp-google-b1-desc": "Collaborated with cross-functional, randomized teams to engineer autonomous logic systems and AI-integrated features, focusing on algorithmic efficiency.",
            "exp-google-b2-title": "Agile Methodology",
            "exp-google-b2-desc": "Applied Agile/Scrum principles to manage product lifecycles and feature prioritization in high-pressure technical environments.",
            "exp-google-b3-title": "Data-Driven MVP Iteration",
            "exp-google-b3-desc": "Analyzed system performance metrics and user feedback loops to iterate on AI-integrated MVPs, optimizing core logic for scalability and market readiness.",

            "exp-tnc-title": "Project Management Intern",
            "exp-tnc-company": "TNC Group",
            "exp-tnc-loc": "Istanbul, Türkiye",
            "exp-tnc-date": "Apr 2025 - May 2025",
            "exp-tnc-b1-title": "Systematic Workflow Management",
            "exp-tnc-b1-desc": "Managed project integration workflows and task prioritization using a systematic approach aligned with real-world legal and regulatory standards.",
            "exp-tnc-b2-title": "Pipeline Coordination",
            "exp-tnc-b2-desc": "Facilitated communication between cross-functional teams, ensuring project documentation and delivery milestones met industry-standard quality benchmarks.",

            "projects-title": "Featured Projects",
            "proj-chess-title": "Project Chess",
            "proj-chess-desc": "Unity 6000 based hybrid tactical board game. Includes synergy engine and card-based drafting system. <br>Click for details..",
            "proj-billio-title": "Flutter_Billio",
            "proj-billio-desc": "Mobile subscription and finance tracking app. Developed using Flutter with modern UI/UX principles. <br>Click for details..",
            "docs-title": "Documents & Archive",
            "docs-desc": "Select the document you wish to review.",
            "doc-cv-title": "Current CV",
            "doc-cv-sub": "PDF Format",
            "doc-cert-title": "Certificates",
            "doc-cert-sub": "Educational Documents",
            "doc-port-title": "Portfolio PDF",
            "doc-port-sub": "Design Documents",
            "doc-drive-title": "GDrive Archive",
            "doc-drive-sub": "All Files",
            "theme-dark": "Switch to Dark Mode",
            "theme-light": "Switch to Light Mode",
            "close": "Close",
            "proj-chess-long-desc": "Project Chess is a modern board game that combines strategic depth with visual richness. Leveraging the power of Unity 6000, players draft cards with unique abilities to build their own strategies. Thanks to the synergy engine, different card combinations create powerful effects that can completely change the course of the game. Detailed system design offers a balanced and competitive experience for both beginners and experienced players.",
            "proj-billio-long-desc": "Flutter_Billio is a comprehensive subscription and finance tracking app designed for modern mobile users. Using the power of Flutter, it offers a seamless experience on both iOS and Android with a single codebase. The app analyzes spending habits, reminds of upcoming payments, and helps users optimize their budgets. Prepared with glassmorphism and minimal design principles, the interface transforms financial tracking from a tedious task into an enjoyable experience.",
            "footer": "© 2026 Alper Kocasalih. All rights reserved."
        },
        es: {
            "nav-home": "Inicio",
            "nav-profile": "Sobre Mí",
            "nav-experience": "Experiencia",
            "nav-projects": "Proyectos",
            "nav-documents": "Documentos",
            "hero-title": "Alper Kocasalih",
            "hero-subtitle": "Diseñador de Juegos y Desarrollador de Software",
            "hero-status": "Diseñador de Juegos Junior | Remoto Amigable | Abierto a Nuevas Oportunidades 🚀",
            "hero-desc": "Estudiante de Diseño de Juegos Digitales en la Universidad Beykent de Estambul. Candidato a desarrollador centrado en la resolución de problemas técnicos y arquitectura de sistemas.",
            "profile-title": "Información Personal",
            "profile-edu": "Educación",
            "profile-uni": "Universidad Beykent",
            "profile-dept": "Diseño de Juegos Digitales",
            "profile-date": "2022 - Presente",
            "profile-skills": "Habilidades",
            "profile-tech": "Conocimiento Técnico",
            "profile-tech-desc": "OOP, SOLID, Design Patterns, Game Mechanics, Technical QA, .NET Core, URP/Shader.",
            "exp-title": "EXPERIENCE",
            "exp-recontact-title": "Technical QA Analyst (Volunteer)",
            "exp-recontact-company": "Recontact Games",
            "exp-recontact-loc": "Istanbul, Türkiye",
            "exp-recontact-date": "Oct 2024 - Dec 2024",
            "exp-recontact-b1-title": "Deep-Level Logic Debugging",
            "exp-recontact-b1-desc": "Identified and documented critical back-end logic errors (including null-pointer/nmed exceptions) by analyzing the interaction between core code and gameplay systems.",
            "exp-recontact-b2-title": "Performance Benchmarking",
            "exp-recontact-b2-desc": "Conducted technical analysis of FPS output and frame-time consistency to determine their impact on gameplay mechanics and player input latency.",
            "exp-recontact-b3-title": "Technical Bug Reporting",
            "exp-recontact-b3-desc": "Provided high-fidelity reports for engineering teams, including root cause analysis of system-level crashes and mechanics failures.",

            "exp-netas-title": "Software & System Test Intern",
            "exp-netas-company": "Netaş Telekomünikasyon A.Ş.",
            "exp-netas-loc": "Istanbul, Türkiye",
            "exp-netas-date": "July 2025 - Sep 2025",
            "exp-netas-b1-title": "Stress & Load Testing",
            "exp-netas-b1-desc": "Conducted \"purpose-defying\" system usage tests to identify breaking points; monitored CPU/GPU load and hardware resource allocation under extreme conditions.",
            "exp-netas-b2-title": "AI System Verification",
            "exp-netas-b2-desc": "Tested AI Chatbot logic and response accuracy, ensuring functional stability and high-performance backend-frontend synchronization.",
            "exp-netas-b3-title": "Mobile Resource Analysis",
            "exp-netas-b3-desc": "Profiled real-time mobile data consumption and optimized technical systems to ensure high stability in data-driven interactive modules.",

            "exp-google-title": "Scholars Participant (Logic Engineering Focus)",
            "exp-google-company": "Google Yapay Zeka ve Teknoloji Akademisi",
            "exp-google-loc": "Istanbul, Türkiye",
            "exp-google-date": "Nov 2024 - Sep 2025",
            "exp-google-b1-title": "Logic Engineering",
            "exp-google-b1-desc": "Collaborated with cross-functional, randomized teams to engineer autonomous logic systems and AI-integrated features, focusing on algorithmic efficiency.",
            "exp-google-b2-title": "Agile Methodology",
            "exp-google-b2-desc": "Applied Agile/Scrum principles to manage product lifecycles and feature prioritization in high-pressure technical environments.",
            "exp-google-b3-title": "Data-Driven MVP Iteration",
            "exp-google-b3-desc": "Analyzed system performance metrics and user feedback loops to iterate on AI-integrated MVPs, optimizing core logic for scalability and market readiness.",

            "exp-tnc-title": "Project Management Intern",
            "exp-tnc-company": "TNC Group",
            "exp-tnc-loc": "Istanbul, Türkiye",
            "exp-tnc-date": "Apr 2025 - May 2025",
            "exp-tnc-b1-title": "Systematic Workflow Management",
            "exp-tnc-b1-desc": "Managed project integration workflows and task prioritization using a systematic approach aligned with real-world legal and regulatory standards.",
            "exp-tnc-b2-title": "Pipeline Coordination",
            "exp-tnc-b2-desc": "Facilitated communication between cross-functional teams, ensuring project documentation and delivery milestones met industry-standard quality benchmarks.",

            "projects-title": "Proyectos Destacados",
            "proj-chess-title": "Project Chess",
            "proj-chess-desc": "Juego de mesa táctico híbrido basado en Unity 6000. Incluye motor de sinergia y sistema de drafting basado en cartas. <br>Haga clic para más detalles..",
            "proj-billio-title": "Flutter_Billio",
            "proj-billio-desc": "Aplicación móvil de suscripción y seguimiento financiero. Desarrollada con Flutter siguiendo principios modernos de UI/UX. <br>Haga clic para más detalles..",
            "docs-title": "Documentos y Archivos",
            "docs-desc": "Seleccione el documento que desea revisar.",
            "doc-cv-title": "CV Actual",
            "doc-cv-sub": "Formato PDF",
            "doc-cert-title": "Certificados",
            "doc-cert-sub": "Documentos Educativos",
            "doc-port-title": "Portafolio PDF",
            "doc-port-sub": "Documentos de Diseño",
            "doc-drive-title": "Archivo GDrive",
            "doc-drive-sub": "Todos los Archivos",
            "theme-dark": "Cambiar a Modo Oscuro",
            "theme-light": "Cambiar a Modo Claro",
            "close": "Cerrar",
            "proj-chess-long-desc": "Project Chess es un juego de mesa moderno que combina profundidad estratégica con riqueza visual. Aprovechando el poder de Unity 6000, los jugadores seleccionan cartas con habilidades únicas para construir sus propias estrategias. Gracias al motor de sinergia, diferentes combinaciones de cartas crean efectos poterosos que pueden cambiar completamente el curso del juego. El diseño detallado del sistema ofrece una experiencia equilibrada y competitiva tanto para principiantes como para jugadores experimentados.",
            "proj-billio-long-desc": "Flutter_Billio es una aplicación integral de seguimiento de suscripciones y finanzas diseñada para usuarios móviles modernos. Utilizando el poder de Flutter, ofrece una experiencia fluida tanto en iOS como en Android con una sola base de código. La aplicación analiza los hábitos de gasto, recuerda los próximos pagos y ayuda a los usuarios a optimizar sus presupuestos. Preparada con glassmorphism y principios de diseño minimalista, la interfaz transforma el seguimiento financiero de una tarea tediosa en una experiencia agradable.",
            "footer": "© 2026 Alper Kocasalih. Todos los derechos reservados."
        }
    },
    skills: ["C#", "Unity", "Flutter", "Dart", "SQL", "C++", "Python"],
    projects: [
        {
            titleKey: "proj-chess-title",
            descKey: "proj-chess-desc",
            longDescKey: "proj-chess-long-desc",
            images: [
                "images/Pawns2.png",
                "images/Pawns.png",
                "images/InGameSS.png",
                "images/Cards.png"
            ],
            tags: ["C#", "Unity 6000", "System Design"],
            link: "#"
        },
        {
            titleKey: "proj-billio-title",
            descKey: "proj-billio-desc",
            longDescKey: "proj-billio-long-desc",
            isMobile: true,
            images: ["images/billio-1.png", "images/billio-2.png"],
            tags: ["Flutter", "Dart", "Mobile Dev"],
            link: "#"
        }
    ],
    experience: [
        {
            companyKey: "exp-netas-company",
            titleKey: "exp-netas-title",
            locationKey: "exp-netas-loc",
            dateKey: "exp-netas-date",
            bullets: [
                { titleKey: "exp-netas-b1-title", descKey: "exp-netas-b1-desc" },
                { titleKey: "exp-netas-b2-title", descKey: "exp-netas-b2-desc" },
                { titleKey: "exp-netas-b3-title", descKey: "exp-netas-b3-desc" }
            ]
        },
        {
            companyKey: "exp-google-company",
            titleKey: "exp-google-title",
            locationKey: "exp-google-loc",
            dateKey: "exp-google-date",
            bullets: [
                { titleKey: "exp-google-b1-title", descKey: "exp-google-b1-desc" },
                { titleKey: "exp-google-b2-title", descKey: "exp-google-b2-desc" },
                { titleKey: "exp-google-b3-title", descKey: "exp-google-b3-desc" }
            ]
        },
        {
            companyKey: "exp-tnc-company",
            titleKey: "exp-tnc-title",
            locationKey: "exp-tnc-loc",
            dateKey: "exp-tnc-date",
            bullets: [
                { titleKey: "exp-tnc-b1-title", descKey: "exp-tnc-b1-desc" },
                { titleKey: "exp-tnc-b2-title", descKey: "exp-tnc-b2-desc" }
            ]
        },
        {
            companyKey: "exp-recontact-company",
            titleKey: "exp-recontact-title",
            locationKey: "exp-recontact-loc",
            dateKey: "exp-recontact-date",
            bullets: [
                { titleKey: "exp-recontact-b1-title", descKey: "exp-recontact-b1-desc" },
                { titleKey: "exp-recontact-b2-title", descKey: "exp-recontact-b2-desc" },
                { titleKey: "exp-recontact-b3-title", descKey: "exp-recontact-b3-desc" }
            ]
        }
    ],
    documents: [
        { titleKey: "doc-cv-title", subKey: "doc-cv-sub", icon: "file-text", link: "#" },
        { titleKey: "doc-cert-title", subKey: "doc-cert-sub", icon: "award", link: "#" },
        { titleKey: "doc-port-title", subKey: "doc-port-sub", icon: "folder-kanban", link: "#" },
        { titleKey: "doc-drive-title", subKey: "doc-drive-sub", icon: "external-link", link: "#" }
    ]
};
