// Global data object to avoid CORS issues with file:// protocol
window.PORTFOLIO_DATA = {
    translations: {
        tr: {
            "nav-home": "Ana Sayfa",
            "nav-profile": "Hakkımda",
            "nav-experience": "Deneyim",
            "nav-projects": "Projeler",
            "nav-documents": "Dökümanlar",
            "hero-title": "Alper Kocasalih",
            "hero-subtitle": "Game Designer & Software Developer",
            "hero-status": "EU Work Permit | Remote Friendly | Available for New Opportunities 🚀",
            "hero-desc": "Istanbul Beykent Üniversitesi Dijital Oyun Tasarımı öğrencisi. Teknik problem çözme ve sistem mimarisi odaklı bir geliştirici adayı.",
            "profile-title": "Kişisel Bilgiler",
            "profile-edu": "Eğitim",
            "profile-uni": "Beykent Üniversitesi",
            "profile-dept": "Dijital Oyun Tasarımı",
            "profile-date": "2022 - Devam Ediyor",
            "profile-skills": "Yetenekler",
            "profile-tech": "Teknik Bilgi",
            "profile-tech-desc": "OOP, SOLID, Design Patterns, Game Mechanics, Technical QA, .NET Core, URP/Shader.",
            "exp-title": "Deneyim",
            "exp-intern-title": "Stajyer | Yazılım",
            "exp-intern-company": "Netaş",
            "exp-intern-desc": "Veritabanı Yapıları & Sistem Testleri üzerine çalışmalar gerçekleştirildi.",
            "exp-qa-title": "Teknik QA",
            "exp-qa-company": "Recontact Games",
            "exp-qa-desc": "Hata Analizi & Teknik Mantık Kontrolü süreçlerinde aktif rol alındı.",
            "projects-title": "Öne Çıkan Projeler",
            "proj-chess-title": "Project Chess",
            "proj-chess-desc": "Unity 6000 tabanlı, hibrit taktiksel masa oyunu. Sinerji motoru ve kart tabanlı drafting sistemi içerir.",
            "proj-billio-title": "Flutter_Billio",
            "proj-billio-desc": "Mobil abonelik ve finans takip uygulaması. Modern UI/UX prensipleriyle Flutter kullanılarak geliştirildi.",
            "docs-title": "Belgeler & Arşiv",
            "docs-desc": "İncelemek istediğiniz dökümanı seçiniz.",
            "doc-cv-title": "Güncel CV",
            "doc-cv-sub": "PDF Formatı",
            "doc-cert-title": "Sertifikalar",
            "doc-cert-sub": "Eğitim Belgeleri",
            "doc-port-title": "Portfolyo PDF",
            "doc-port-sub": "Tasarım Belgeleri",
            "doc-drive-title": "GDrive Arşivi",
            "doc-drive-sub": "Tüm Dosyalar",
            "theme-dark": "Karanlık Moda Geç",
            "theme-light": "Aydınlık Moda Geç",
            "footer": "© 2026 Alper Kocasalih. Tüm hakları saklıdır."
        },
        en: {
            "nav-home": "Home",
            "nav-profile": "About Me",
            "nav-experience": "Experience",
            "nav-projects": "Projects",
            "nav-documents": "Documents",
            "hero-title": "Alper Kocasalih",
            "hero-subtitle": "Game Designer & Software Developer",
            "hero-status": "Junior Game Designer | Remote Friendly | Available for New Opportunities 🚀",
            "hero-desc": "Digital Game Design student at Istanbul Beykent University. Developer candidate focused on technical problem solving and system architecture.",
            "profile-title": "Personal Information",
            "profile-edu": "Education",
            "profile-uni": "Beykent University",
            "profile-dept": "Digital Game Design",
            "profile-date": "2022 - Present",
            "profile-skills": "Skills",
            "profile-tech": "Technical Knowledge",
            "profile-tech-desc": "OOP, SOLID, Design Patterns, Game Mechanics, Technical QA, .NET Core, URP/Shader.",
            "exp-title": "Experience",
            "exp-intern-title": "Software Intern",
            "exp-intern-company": "Netaş",
            "exp-intern-desc": "Conducted studies on database structures and system testing.",
            "exp-qa-title": "Technical QA",
            "exp-qa-company": "Recontact Games",
            "exp-qa-desc": "Actively involved in error analysis and technical logic control processes.",
            "projects-title": "Featured Projects",
            "proj-chess-title": "Project Chess",
            "proj-chess-desc": "Unity 6000 based hybrid tactical board game. Includes synergy engine and card-based drafting system.",
            "proj-billio-title": "Flutter_Billio",
            "proj-billio-desc": "Mobile subscription and finance tracking app. Developed using Flutter with modern UI/UX principles.",
            "docs-title": "Documents & Archive",
            "docs-desc": "Select the document you wish to review.",
            "doc-cv-title": "Current CV",
            "doc-cv-sub": "PDF Format",
            "doc-cert-title": "Certificates",
            "doc-cert-sub": "Educational Documents",
            "doc-port-title": "Portfolio PDF",
            "doc-port-sub": "Design Documents",
            "doc-drive-title": "GDrive Archive",
            "doc-drive-sub": "All Files",
            "theme-dark": "Switch to Dark Mode",
            "theme-light": "Switch to Light Mode",
            "footer": "© 2026 Alper Kocasalih. All rights reserved."
        },
        es: {
            "nav-home": "Inicio",
            "nav-profile": "Sobre Mí",
            "nav-experience": "Experiencia",
            "nav-projects": "Proyectos",
            "nav-documents": "Documentos",
            "hero-title": "Alper Kocasalih",
            "hero-subtitle": "Diseñador de Juegos y Desarrollador de Software",
            "hero-status": "Diseñador de Juegos Junior | Remoto Amigable | Abierto a Nuevas Oportunidades 🚀",
            "hero-desc": "Estudiante de Diseño de Juegos Digitales en la Universidad Beykent de Estambul. Candidato a desarrollador centrado en la resolución de problemas técnicos y arquitectura de sistemas.",
            "profile-title": "Información Personal",
            "profile-edu": "Educación",
            "profile-uni": "Universidad Beykent",
            "profile-dept": "Diseño de Juegos Digitales",
            "profile-date": "2022 - Presente",
            "profile-skills": "Habilidades",
            "profile-tech": "Conocimiento Técnico",
            "profile-tech-desc": "OOP, SOLID, Design Patterns, Game Mechanics, Technical QA, .NET Core, URP/Shader.",
            "exp-title": "Experiencia",
            "exp-intern-title": "Pasante de Software",
            "exp-intern-company": "Netaş",
            "exp-intern-desc": "Realicé estudios sobre estructuras de bases de datos ve pruebas de sistemas.",
            "exp-qa-title": "Control de Calidad Técnico",
            "exp-qa-company": "Recontact Games",
            "exp-qa-desc": "Involucrado activamente en procesos de análisis de errores y control de lógica técnica.",
            "projects-title": "Proyectos Destacados",
            "proj-chess-title": "Project Chess",
            "proj-chess-desc": "Juego de mesa táctico híbrido basado en Unity 6000. Incluye motor de sinergia ve sistema de drafting basado en cartas.",
            "proj-billio-title": "Flutter_Billio",
            "proj-billio-desc": "Aplicación móvil de suscripción ve seguimiento financiero. Desarrollada con Flutter siguiendo principios modernos de UI/UX.",
            "docs-title": "Documentos y Archivos",
            "docs-desc": "Seleccione el documento que desea revisar.",
            "doc-cv-title": "CV Actual",
            "doc-cv-sub": "Formato PDF",
            "doc-cert-title": "Certificados",
            "doc-cert-sub": "Documentos Educativos",
            "doc-port-title": "Portafolio PDF",
            "doc-port-sub": "Documentos de Diseño",
            "doc-drive-title": "Archivo GDrive",
            "doc-drive-sub": "Todos los Archivos",
            "theme-dark": "Cambiar a Modo Oscuro",
            "theme-light": "Cambiar a Modo Claro",
            "footer": "© 2026 Alper Kocasalih. Todos los derechos reservados."
        }
    },
    skills: ["C#", "Unity", "Flutter", "Dart", "SQL", "C++", "Python"],
    projects: [
        {
            titleKey: "proj-chess-title",
            descKey: "proj-chess-desc",
            tags: ["C#", "Unity 6000", "System Design"],
            link: "#"
        },
        {
            titleKey: "proj-billio-title",
            descKey: "proj-billio-desc",
            tags: ["Flutter", "Dart", "Mobile Dev"],
            link: "#"
        }
    ],
    experience: [
        {
            titleKey: "exp-intern-title",
            companyKey: "exp-intern-company",
            descKey: "exp-intern-desc",
            date: "2023"
        },
        {
            titleKey: "exp-qa-title",
            companyKey: "exp-qa-company",
            descKey: "exp-qa-desc",
            date: "2024"
        }
    ],
    documents: [
        { titleKey: "doc-cv-title", subKey: "doc-cv-sub", icon: "file-text", link: "#" },
        { titleKey: "doc-cert-title", subKey: "doc-cert-sub", icon: "award", link: "#" },
        { titleKey: "doc-port-title", subKey: "doc-port-sub", icon: "folder-kanban", link: "#" },
        { titleKey: "doc-drive-title", subKey: "doc-drive-sub", icon: "external-link", link: "#" }
    ]
};
